%YAML 1.2
---

# logging config for pymoskito package
version: 1
disable_existing_loggers: true

# default logger
root:
  level: !!python/name:logging.NOTSET
  handlers: [logfile, console]

loggers:
  #SimGUI_window is created on startup

  SimGUI_file:
    level: !!python/name:logging.WARN
    handlers: [logfile]
    qualname: sim_gui
    propagate: false

handlers:

  # log everything
  logfile:
    class: logging.handlers.RotatingFileHandler
    filename: pymoskito.log
    formatter: simpleFormatter
    level: !!python/name:logging.NOTSET
    maxBytes: 100000
    backupCount: 3

  # display some data on cmd-line
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simpleFormatter
    level: !!python/name:logging.NOTSET

formatters:

    simpleFormatter:
      class: logging.Formatter
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'

#    commandlineFormatter:
#      class: !!python/name:logging.Formatter
#      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
#      datefmt: '%d/%m/%Y %H:%M:%S'
...
